[package]
name = "enemy-speed-randomizer-bom"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
fromsoftware-shared.workspace = true
eldenring.workspace = true
hudhook.workspace = true
rand = "0.9"
serde.workspace = true
toml.workspace = true
windows = { workspace = true, features = ["Win32_System_Diagnostics_Debug", "Win32_System_LibraryLoader", "Win32_UI_WindowsAndMessaging"] }

[lib]
name = "enemy_speed_randomizer_bom"
crate-type = ["cdylib"]
